instagram/post/urls.py
from django.conf.urls import url

from post import views

urlpatterns = [
    # Post
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^delete/(?P<post_pk>\d+)/$', views.post_delete, name='post_delete'),
    url(r'^(?P<post_pk>\d+)/like-toggle', views.post_like_toggle, name='post_like_toggle'),

    # Comment
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
    url(r'^comment/(?P<comment_pk>\d+)/delete/', views.comment_delete, name='comment_delete'),
]

instagram/sms/urls.py
from django.conf.urls import url

from . import apis

urlpatterns = [
    url(r'^send-sms/$', apis.SendSMS.as_view(), name='sms')
]

instagram/post/models.py
from django.conf import settings
from django.db import models


class PostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(author=None)


class Post(models.Model):
    photo = models.ImageField(upload_to='post')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True)
    objects = PostManager()

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'Post (PK: {self.pk})'


class PostComment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True)
    post = models.ForeignKey(Post, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # 가장 나중에 달린 Comment가 가장 나중에 오도록 ordering설정p
        ordering = ['created_at']

instagram/post/forms.py
from django import forms

from .models import Post, PostComment

__all__ = (
    'PostForm',
)


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = (
            'photo',
        )

    def save(self, commit=True, *args, **kwargs):
        if not self.instance.pk and commit:
            author = kwargs.pop('author', None)
            if not author:
                raise ValueError('Author field is required')
            self.instance.author = author
        return super().save(*args, **kwargs)


class CommentForm(forms.ModelForm):

    class Meta:
        model = PostComment
        fields = (
            'content',
        )
        widgets = {
            'content': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }

instagram/config/urls/views.py
from django.conf.urls import url, include
from django.contrib import admin

from .. import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Post application
    url(r'^post/', include('post.urls.views', namespace='post')),

    # Member application
    url(r'^members/', include('member.urls.views', namespace='member')),
    #
    # config
    url(r'^$', views.index, name='index'),
    ]

instagram/member/urls/views.py
from django.conf.urls import url

from .. import views

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='signin'),
    url(r'^logout/$', views.logout, name='signout'),
    url(r'^profile/(?P<user_pk>\d+)/$', views.profile, name='profile'),
    url(r'^facebook-login/$', views.facebook_login, name='facebook_login'),
    url(r'^follow/(?P<user_pk>\d+)/$', views.follow_toggle, name='follow_toggle'),
    url(r'^front-facebook-login/$', views.FrontFacebookLogin.as_view(), name='front-facebook-login'),
]

instagram/post/urls/views.py
from django.conf.urls import url

from .. import views

urlpatterns = [
    # Post
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^delete/(?P<post_pk>\d+)/$', views.post_delete, name='post_delete'),
    url(r'^(?P<post_pk>\d+)/like-toggle', views.post_like_toggle, name='post_like_toggle'),

    # Comment
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
    url(r'^comment/(?P<comment_pk>\d+)/delete/', views.comment_delete, name='comment_delete'),
]

instagram/post/views/comment.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect

from ..forms import CommentForm
from ..models import Post, PostComment

__all__ = (
    'comment_create',
    'comment_delete'
)


def comment_create(request, post_pk):
    """
    post_pk에 해당하는 Post에 연결된 PostComment를 작성
    PostComment Form을 생성해서 사용
    기본적인 루틴은 위의 post_create와 같음
    :param request:
    :param post_pk:
    :return:
    """
    # URL get parameter로 온 'post_pk'에 해당하는
    # Post instance를 'post'변수에 할당
    # 찾지못하면 404Error를 브라우저에 리턴
    if not request.user.is_authenticated:
        return redirect('member:signin')
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        # 데이터가 바인딩된 CommentForm인스턴스를 form에 할당
        form = CommentForm(request.POST)
        # 유효성 검증
        if form.is_valid():
            # 통과한 경우, post에 해당하는 Comment인스턴스를 생성
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            # 생성 후 Post의 detail화면으로 이동
            next = request.GET.get('next', '').strip()
            if next:
                return redirect(next)
            return redirect('post:post_list')


def comment_delete(request, comment_pk):
    next_path = request.GET.get('next').strip()
    if request.method == 'POST':
        comment = get_object_or_404(PostComment, pk=comment_pk)
        if comment.author == request.user:
            comment.delete()
            if next_path:
                return redirect(next_path)

            return redirect('post:post_detail', post_pk=comment.post.pk)
        else:
            raise PermissionDenied('작성자가 아닙니다')

instagram/post/views/post.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect

from ..forms import PostForm, CommentForm
from ..models import Post

__all__ = (
    'post_list',
    'post_create',
    'post_delete',
    'post_detail',
    'post_like_toggle',
)


def post_list(request):
    """
    모든 Post목록을 리턴
    template은 'post/post_list.html'을 사용
    :param request:
    :return:
    """
    posts = Post.objects.exclude(author=None)
    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'post/post_list.html', context)


@login_required
def post_create(request):
    """
    1. 이 뷰에 접근할 때 해당 사용자가 인증된 상태가 아니면 로그인 뷰로 redirect
    2. form.is_valid()를 통과한 후, 생성하는 Post객체에 author정보를 추가
    :param request:
    :return:
    """
    if not request.user.is_authenticated:
        return redirect('member:signin')
    if request.method == 'POST':
        # POST요청의 경우 PostForm인스턴스 생성과정에서 request.POST, request.FILES를 사용
        form = PostForm(request.POST, request.FILES)
        # form생성과정에서 전달된 데이터들이 Form의 모든 field들에 유효한지 검사
        if form.is_valid():
            # 유효할 경우 Post인스턴스를 생성 및 저장
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:post_list')
    else:
        # GET요청의 경우, 빈 PostForm인스턴스를 생성해서 템플릿에 전달
        form = PostForm()

        # GET요청에선 이부분이 무조건 실행
        # POST요청에선 form.is_valid()를 통과하지 못하면 이부분이 실행
    context = {
        'form': form,
    }
    return render(request, 'post/post_create.html', context)


def post_delete(request, post_pk):
    if request.method == 'POST':
        # post_pk에 해당하는 Post가 있는지 검사
        post = get_object_or_404(Post, pk=post_pk)
        # request.user가 Post의 author인지 검사
        if post.author == request.user:
            post.delete()
            return redirect('post:post_list')
        else:
            raise PermissionDenied('작성자가 아닙니다')


def post_detail(request, post_pk):
    # 해당 post의 사진을 img태그로 출력
    # 1. view작성
    #   1-1. post_pk에 해당하는 Post객체를
    #           post변수에 할당해서
    #           post라는 키로 context에 할당해서 render에 전달
    #   1-2. 템플릿은 post/post_detail.html사용

    # 2. url작성
    #   2-1. urls.py에 '/post/<post_pk>/에 해당하는 url에 이 view를 연결

    # 3. 템플릿 작성
    #   3-1. post/post_detail.html을 생성, 전달받은 'post'변수의
    #       photo필드의 url속성을 이용해 img태그 출력

    # 4. base템플릿 작성 및 'extend'템플릿태그 사용
    #   html:5 emmet을 사용, 기본이 되는 base.html을 작성, 나머지 템플릿에서 해당 템플릿을 extend
    #   내용은 'content' block에 채운다
    # post = Post.objects.get(pk=post_pk)
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,

    }
    return render(request, 'post/post_detail.html', context)


@login_required
def post_like_toggle(request, post_pk):
    """
      1. view, url연결
          /post/<post_pk>/like-toggle/
      2. 로직구현
          post_pk에 해당하는 Post가
          현재 로그인한 유저의 like_posts에 있다면 없애고
          like_posts에 없다면 추가
      3. post.html에서 현재 user가 해당 post를 like했는지 여부 표시
          {% if <A> in <B> %}
      4. post.html에서 이 뷰로 요청을 보낼 수 있는 form구현
      :param request:
      :param post_pk:
      :return:
      """
    # GET파라미터로 전달된 이동할 URL
    if request.method == 'POST':
        next_path = request.GET.get('next')

        # post_pk에 해당하는 Post객체
        post = get_object_or_404(Post, pk=post_pk)

        # 요청한 사용자
        user = request.user

        # 사용자의 like_posts목록에서 like_toggle할 Post가 있는지 확인
        filtered_like_posts = user.like_posts.filter(pk=post.pk)
        # 존재할경우, like_posts목록에서 해당 Post를 삭제
        if filtered_like_posts.exists():
            user.like_posts.remove(post)
        # 없을 경우, like_posts목록에 해당 Post를 추가
        else:
            user.like_posts.add(post)

        # 이동할 path가 존재할 경우 해당 위치로, 없을 경우 Post상세페이지로 이동
        if next_path:
            return redirect(next_path)
        return redirect('post:post_detail', post_pk=post_pk)

templates/include/form-horizontal.html
<form action="" method="POST" enctype="{{ enctype }}" class="form-horizontal">
	{% csrf_token %}
	{% for field in form %}
	<div class="form-group{% if field.errors %} has-error{% endif %}">
		<label
			for="{{ field.auto_id }}"
			class="col-xs-2 control-label">
			{{ field.label }}
		</label>
		<div class="col-xs-10">
			{{ field }}
			{% if field.errors %}
				{% for error in field.errors %}
				<span class="help-block">{{ error }}</span>
				{% endfor %}
			{% endif %}
		</div>
	</div>
	{% endfor %}
	{% if form.non_field_errors %}
		{% for error in form.non_field_errors %}
		<p class="text-danger">{{ error }}</p>
		{% endfor %}
	{% endif %}
	<button class="btn btn-primary btn-block">{{ submit_text }}</button>
</form>

templates/include/post.html
<div id="post-{{ post.pk }}" class="panel panel-default post">
	<div class="panel-heading">
		<span><a href="{% url 'member:profile' user_pk=post.author.pk %}">{{ post.author.username }}</a></span>

		{% if post.author == user %}
		<form action="{% url 'post:post_delete' post_pk=post.pk %}" method="post">
			{% csrf_token %}
			<button class="btn btn-danger btn-xs">삭제</button>
		</form>
		{% endif %}
	</div>
	<div class="panel-body">
		<a href="{% url 'post:post_detail' post_pk=post.pk %}">
			<img src="{{ post.photo.url }}" class="img-post">
		</a>
		<div class="body-content">
            <div class="btn-container">
                <form action="{% url 'post:post_like_toggle' post_pk=post.pk %}?next=
						{% if post_type == 'list' %}
							{% url 'post:post_list' %}#post-{{ post.pk }}
						{% elif post_type == 'detail' %}
							{% url 'post:post_detail' post_pk=post.pk %}
						{% endif %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-default border-none" aria-label="Like button">
					  <span
                              class="glyphicon
						    {% if post in user.like_posts.all %}
						      glyphicon-heart
								{% else %}
									glyphicon-heart-empty
								{% endif %}"
                              aria-hidden="true"></span>
                    </button>
                </form>
            </div>
			<ul id="post-comments-{{ post.pk }}">
				{% for comment in post.comments.all %}
				<li>
					<span>
						<a href="{% url 'member:profile' user_pk=comment.author.pk %}">
							{{ comment.author.username }} : </a>
					</span>
					<span>{{ comment.content }}</span>
					{% if comment.author == user %}
					<form action="{% url 'post:comment_delete' comment_pk=comment.pk %}?next=
						{% if post_type == 'list' %}
							{% url 'post:post_list' %}#post-{{ post.pk }}
						{% elif post_type == 'detail' %}
							{% url 'post:post_detail' post_pk=post.pk %}
						{% endif %}"
						method="post" class="form-inline">
						{% csrf_token %}
						<button class="btn btn-danger btn-xs">삭제</button>
					</form>
					{% endif %}
				</li>
				{% endfor %}
			</ul>
			<form
				action="{% url 'post:comment_create' post_pk=post.pk %}?next=
				{% if post_type == 'list' %}
					{% url 'post:post_list' %}#post-{{ post.pk }}
				{% elif post_type == 'detail' %}
					{% url 'post:post_detail' post_pk=post.pk %}
				{% endif %}"
				method="POST">
				{% csrf_token %}
				{{ comment_form }}
				<button class="btn btn-primary btn-block">댓글달기</button>
			</form>
		</div>
	</div>
</div>